### ISSUE TITLE
Things on my TODO list

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#321]
### Documentation
- [ ] Create a GitHub pages site to host Jazzy Docs
- [ ] Finish documenting public APIs with Xcode comments
- [ ] QuickStart.md
- [ ] FAQs.md
- [ ] Add Screenshots to README

### Testing
- [ ] Increase Test Coverage 😝 

### Performance Tuning / Improvements
- [ ] MessageStyle class
- [ ] MessageLabel class

### Example App
(Probably not worth working on until I fix `MessageStyle`)
- [ ] Add example of iMessage UI (I want to mimic it **exactly**)
- [ ] Google Hangouts would be another good example

**Comment by SD10** [comment]
I'm closing this issue because it has been working great! 😅 😅 😅
