### ISSUE TITLE
Add AvatarView subclass to MessagesCollectionViewCell

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#34]
## Add AvatarView subclass to MessagesCollectionViewCell

Basically, we need to revert some of the changes made to `MessagesDisplayDelegate` to return a configuration representing the `AvatarView` instead of the `AvatarView` itself. As discussed on Slack.

### TODO:
- [x] Add back `Avatar` model representing configuration for `AvatarView`
- [x] Replace `avatarImageView` in `MessagesCollectionViewCell` with `AvatarView`
- [x] Move `AvatarView.playground` to `ChatExample` project

Please submit changes to `v0.3.0` branch 😃
