### ISSUE TITLE
MessageKit v1.0 Requirements

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#456]
This is a list of rather arbitrary MessageKit v1.0 requirements. If you're using MessageKit in production or have some input on this topic, please comment below:

**Features**
- [ ] Refactor MessageStyle to use `CAShapeLayer` and remove dependency on images #324 #307 
- [X] Add support for copy and paste message content #422 
- [X] Support loading async avatars #164 #421
- [ ] Support loading async message content #421 
- [X] Maintain scroll position after loading new messages #186 
- [x] Add documentation around custom cells and make sure a convenient API is accessible #453 #396 
- [ ] Support both LTR and RTL languages #192 
- [ ] Add accessory view to the cells #432 #190
- [ ] Typing indicator support as last message in `MessagesCollectionView` #191 
- [ ] Load more messages / refresh view #441
- [ ] Support audio messages with iMessage style UI #149 
- [x] Resolve the annoying caching of cellBottomLabel & cellTopLabel size. Allow static sizes? #234 
- [x] Consider removing the 1 message to 1 section ratio #74 
- [ ] Consider adding cells for `Delivered`, `Sent`, `Read`, messages
- [ ] Allow more customization of `AvatarView` #418, #419 

**Review**
- [ ] Review message headers and footers
- [ ] Review the entire API

**Comment by otymartin** [comment]
@nathantannar4 Don't know if this is already supported as i've only played with the example project but would be great if iMessageStyle 'inputView' could have send button outside 'inputTextView'

**Comment by MacMeDan** [comment]
I don't know that 
> Review message headers and footers
really has an action item associated with it. same goes for 
> Review the entire API
Although I think they are good things to do I don't know that they need to be on this list. IMO

**Comment by MacMeDan** [comment]
@otymartin I believe this is already supported. You can add buttons (Which I believe includes the send) button to basically any side of the input view.

**Comment by otymartin** [comment]
@MacMeDan wonderful thanks for the insight

**Comment by SD10** [comment]
> Review message headers and footers
really has an action item associated with it. same goes for
Review the entire API
Although I think they are good things to do I don't know that they need to be on this list. IMO

@MacMeDan I think the list does a poor job of explaining these, but for a `v1.0` I think it is important to review the entire API because while we will still be breaking the API after the release, I hope to do so less significantly. This is the time to make harsh API changes like if we were to rename `MessageType` for example.

About the headers and footers: I've neglected them 😕 That's just a reminder to myself to review them before setting things in stone. 

I'll pull these down into a review category

**Comment by MacMeDan** [comment]
@SD10 Excellent, I think the changes you made there are perfect. It just seemed like this list was primarily a list of thing that were actionable items except those two. I appreciate the distinction of sections 💯 .

**Comment by MacMeDan** [comment]
These two tasks may be very related and effect each other based on the decisions that are made.
>  -[ ] Consider removing the 1 message to 1 section ratio #74
>  -[ ] Consider adding cells for Delivered, Sent, Read, messages

Mostly if you keep section to messages ratio of 1-1 you could add different cells to a section i.e a Status confirmation cell.

just a thought.

**Comment by guoweikun621** [comment]
Good！Expect support for audio messages. Thx

**Comment by guoweikun621** [comment]
When do you release version 1.0? @SD10 Thanks！

**Comment by SD10** [comment]
@guoweikun621 Not sure? #491 would be a huge step forward. We could always use some help 😄

**Comment by SD10** [comment]
Got #491 merged in, which resolves two things on this list 👍

**Comment by SD10** [comment]
Going to close this because we aren't going to add new functionality for 1.0.

The next version contains pretty devastating changes in order to fix fatal flaws. You can see everything we're considering in the [1.0 miletsone](https://github.com/MessageKit/MessageKit/milestone/16).

After 1.0 new functionality will be considered.
